Repository wecode-bootcamp-korea/44-backend-westagram-2, pull requests merged in 2023-03, with the labels that each got.

#4 [최상현] Assignment 1: Express-API 초기 환경 세팅
  .gitignore
  app.js
  package-lock.json
  package.json
Labels: 완료

#8 [왕광현] Assignment 1: Express API - 초기 환경 세팅
  kwanghyun/.env.sample
  kwanghyun/.gitignore
  kwanghyun/app.js
  kwanghyun/package-lock.json
  kwanghyun/package.json
Labels: 완료

#13 [장다희] Assignment 1: Express API - 초기 환경 세팅
  dahee/.env.sample
  dahee/.gitignore
  dahee/app.js
  dahee/package-lock.json
  dahee/package.json
Labels: 멘토 리뷰 요청

#5 [44기 임성근][ADD]:Express 초기 환경세팅
  seong-geun/.env.sample
  seong-geun/.gitignore
  seong-geun/app.js
  seong-geun/package-lock.json
  seong-geun/package.json
Labels: 리뷰 진행 중

#11 [왕광현] Assignment 2: Express-API 유저 회원가입 하기
  kwanghyun/app.js
  kwanghyun/db/migrations/20230322010630_create_users.sql
  kwanghyun/db/migrations/20230322012013_create_posts.sql
  kwanghyun/db/migrations/20230322045358_create_commnets.sql
  kwanghyun/db/migrations/20230323071526_create_likes.sql
Labels: 리뷰 진행 중

#14 [장다희] Assignment 2: Express API - 유저 회원가입
  dahee/.gitignore
  dahee/app.js
  dahee/db/migrations/20230323062911_create_users_table.sql
  dahee/db/migrations/20230323062918_create_posts_table.sql
  dahee/db/migrations/20230323062927_create_likes_table.sql
  dahee/db/migrations/20230323063028_create_comments_table.sql
Labels: 멘토 리뷰 요청

#19 [최상현] assignment2 Express 기본 환경 설정 및 회원가입 구현
  Sanghyun/.gitignore
  Sanghyun/app.js
  Sanghyun/db/migrations/20230322052304_users.sql
  Sanghyun/db/migrations/20230322052311_posts.sql
  Sanghyun/db/migrations/20230322052321_likes.sql
  Sanghyun/db/migrations/20230322132256_contents.sql
  Sanghyun/db/migrations/20230323111817_posts.sql
Labels: 완료

#17 [임성근] Assignment 2: Express-API 유저 회원가입하기
  seong-geun/app.js
  seong-geun/db/migrations/20230324052606_create_users_table.sql
  seong-geun/package-lock.json
  seong-geun/package.json
Labels: 완료

#18 [왕광현] Assignment 3, 4, 5: Express API - CRUD(1)
  kwanghyun/app.js
Labels: 완료

#16 [장다희] Assignment 3,4,5: Express API - 게시글 등록, 전체 게시글, 유저의 게시글 조회
  dahee/app.js
Labels: 완료

#22 [최상현] Assignment 3, 4, 5: Express API - CRUD(1)
  Sanghyun/app.js
  Sanghyun/db/migrations/20230324071142_drop_users_table.sql
Labels: 완료

#20 [장다희] Assignment 6,7,8: Express API - 게시글 수정/삭제, 좋아요 누르기
  dahee/app.js
Labels: 완료

#21 [왕광현] Assignment 6, 7, 8: Express API - CRUD(2)
  kwanghyun/app.js
Labels: 완료

#24 [임성근] Assignment 3,4,5,: Express API - CRUI(1)
  seong-geun/.gitignore
  seong-geun/app.js
  seong-geun/db/migrations/20230324062127_create_posts_table.sql
Labels: 완료

#25 [임성근] Assignment 6,7,8: Express API - CRUD(2)
  seong-geun/app.js
  seong-geun/db/migrations/20230326172301_create_likes_table.sql
Labels: 완료

#23 [최상현] Assignment 6, 7, 8: Express API - CRUD(2)
  Sanghyun/.gitignore
  Sanghyun/app.js
  Sanghyun/db/migrations/20230324054748_likes_create_unique_key.sql
Labels: 완료

#26 [장다희] Assignment - Layered Pattern Refactoring
  dahee/app.js
  dahee/controllers/likeController.js
  dahee/controllers/postController.js
  dahee/controllers/userController.js
  dahee/models/appDataSource.js
  dahee/models/likeDao.js
  dahee/models/postDao.js
  dahee/models/userDao.js
  dahee/routes/index.js
  dahee/routes/likeRouter.js
  dahee/routes/postRouter.js
  dahee/routes/userRouter.js
  dahee/services/likeService.js
  dahee/services/postService.js
  dahee/services/userService.js
Labels: 멘토 리뷰 요청

#27 [왕광현]Assignment1 : LayeredPattern
  kwanghyun/app.js
  kwanghyun/controllers/likeControllers.js
  kwanghyun/controllers/postControllers.js
  kwanghyun/controllers/userControllers.js
  kwanghyun/models/appDataSource.js
  kwanghyun/models/likeDao.js
  kwanghyun/models/postDao.js
  kwanghyun/models/userDao.js
  kwanghyun/routes/index.js
  kwanghyun/routes/likeRouter.js
  kwanghyun/routes/postRouter.js
  kwanghyun/routes/userRouter.js
  kwanghyun/services/likeService.js
  kwanghyun/services/postService.js
  kwanghyun/services/userService.js
Labels: 멘토 리뷰 요청

#29 [최상현] Assignment - Layered Pattern Refactoring
  Sanghyun/app.js
  Sanghyun/controllers/likeController.js
  Sanghyun/controllers/postController.js
  Sanghyun/controllers/userController.js
  Sanghyun/models/likeDao.js
  Sanghyun/models/myDataSources.js
  Sanghyun/models/postDao.js
  Sanghyun/models/userDao.js
  Sanghyun/package.json
  Sanghyun/routes/index.js
  Sanghyun/routes/likeRouter.js
  Sanghyun/routes/postRouter.js
  Sanghyun/routes/userRouter.js
  Sanghyun/services/likeService.js
  Sanghyun/services/postService.js
  Sanghyun/services/userService.js
Labels: 수정 요청

#30 [장다희] Assignmet-인증&인가
  dahee/controllers/postController.js
  dahee/controllers/userController.js
  dahee/models/userDao.js
  dahee/package-lock.json
  dahee/package.json
  dahee/routes/postRouter.js
  dahee/routes/userRouter.js
  dahee/services/userService.js
  dahee/utils/auth.js
Labels: 완료

#31 [임성근]: API Project Structure(Layered Pattern) 적용
  seong-geun/app.js
  seong-geun/controllers/likeController.js
  seong-geun/controllers/postController.js
  seong-geun/controllers/userController.js
  seong-geun/db/migrations/20230324052606_create_users_table.sql
  seong-geun/db/migrations/20230328023530_modify_users_table.sql
  seong-geun/models/appDataSource.js
  seong-geun/models/likeDao.js
  seong-geun/models/postDao.js
  seong-geun/models/userDao.js
  seong-geun/routes/index.js
  seong-geun/routes/likeRouter.js
  seong-geun/routes/postRouter.js
  seong-geun/routes/userRouter.js
  seong-geun/services/likeService.js
  seong-geun/services/postService.js
  seong-geun/services/userService.js
Labels: 완료
